import 'infoDatatype.dart';

List<Flutterdevelopers> dataList = [
  Flutterdevelopers(
    name: 'Gaurang',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/Gaurang__07',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/Gaurangseven',
    userimagename: 'gimage',
  ),
  Flutterdevelopers(
    name: 'Cairo',
    title: 'Flutter Eng.',
    twitterlink: 'https://twitter.com/LeslieKimmy',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/LeslieKimmy',
    userimagename: 'cairoimage',
  ),
  Flutterdevelopers(
    name: 'Anna',
    title: 'Flutter Jr',
    twitterlink: 'https://twitter.com/emily_anna1995',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/emily_anna1995',
    userimagename: 'annaimage',
  ),
  Flutterdevelopers(
    name: 'Peter',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/',
    userimagename: 'peterimage',
  ),
  Flutterdevelopers(
    name: 'Terry',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/',
    userimagename: 'terryimage',
  ),
  Flutterdevelopers(
    name: 'Shweta Vishwakarma',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/ShwetaVish31',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/shwetavish',
    userimagename: 'svimage',
  ),
  Flutterdevelopers(
    name: 'Abhay Patgar',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/united_emotion',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/darkbits018',
    userimagename: 'apimage',
  ),
  Flutterdevelopers(
    name: 'Jay Nirmal',
    title: 'Flutter Dev',
    twitterlink: 'https://twitter.com/Jaynirmal5',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/Jaynirmal31109',
    userimagename: 'jnimage',
  ),
  Flutterdevelopers(
    name: 'Tejas gaikwad',
    title: 'Flutter developer',
    twitterlink: 'https://twitter.com/tejasg0504',
    instalink: 'https://instagram.com/tejas00777',
    githublink: 'https://github.com/Tejas-gaikwad',
    userimagename: 'tgimage',
  ),
  Flutterdevelopers(
    name: 'Mbah Anya',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/EyesNna',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/nnaeyes6',
    userimagename: 'anyaMbah',
  ),
  Flutterdevelopers(
    name: 'Tirth Patel',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/Tirthkp',
    instalink: 'www.instagram.com/tirthkp',
    githublink: 'https://github.com/tirthkp',
    userimagename: 'tpimage',
  ),
  Flutterdevelopers(
    name: 'Ruchit Soni',
    title: 'Flutter Dev',
    twitterlink: 'https://twitter.com/RuchitSoni10',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/ruchit-7span',
    userimagename: 'rsimage',
  ),
  Flutterdevelopers(
   name: 'Sajib Adhikary',
   title: 'Flutter And Web Dev',
   twitterlink: 'ehttps://twitter.com/sajibAdhi',
   instalink: 'www.instagram.com/sajibadhi',
   githublink: 'https://github.com/sajibAdhi',
   userimagename: 'saimage',
 ),
 Flutterdevelopers(
    name: 'Parth Panchal',
    title: 'Flutter & Python Dev',
    twitterlink: 'https://twitter.com/hitchhickerrr',
    instalink: 'www.instagram.com/hitchhicker.tech',
    githublink: 'https://github.com/hitchhicker007',
    userimagename: 'hhimage',
  ),
  Flutterdevelopers(
    name: 'Mohammed Moinuddin',
    title: 'Flutter Dev',
    githublink: 'https://github.com/moinuddin9777',
    instalink: 'https://www.instagram.com/moinuddin9777',
    twitterlink: 'https://twittwe.com/Moin971',
    userimagename: 'mmimage',
  ),
  Flutterdevelopers(
    name: 'Kumar',
    title: 'Flutter Developer',
    githublink: 'https://github.com/0x01-itsmurphy',
    instalink: 'https://www.instagram.com/0x01-itsmurphy',
    twitterlink: 'https://twittwe.com/0x01-itsmurphy',
    userimagename: '0x01-itsmurphy',
  ),
   Flutterdevelopers(
    name: 'Chetan',
    title: 'Flutter DEV',
    twitterlink: 'https://twitter.com/theextrovert0',
    instalink: 'https://www.instagram.com/Widget__yard/',
    githublink: 'https://github.com/Palchetan07',
    userimagename: 'cpimage',
  ),
  Flutterdevelopers(
   name: 'Mukund Jogi',
   title: 'Flutter and Android Dev.',
   twitterlink: 'https://twitter.com/mukundjogi',
   instalink: 'https://www.instagram.com/mukund.a.jogi',
   githublink: 'https://github.com/mukundjogi',
   userimagename: 'mjimage',
 ),
];

