import 'infoDatatype.dart';

List<Flutterdevelopers> dataList = [
  Flutterdevelopers(
    name: 'Gaurang',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/Gaurang__07',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/Gaurangseven',
    userimagename: 'gimage',
  ),
  Flutterdevelopers(
    name: 'Cairo',
    title: 'Flutter Eng.',
    twitterlink: 'https://twitter.com/LeslieKimmy',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/LeslieKimmy',
    userimagename: 'cairoimage',
  ),
  Flutterdevelopers(
    name: 'Anna',
    title: 'Flutter Jr',
    twitterlink: 'https://twitter.com/emily_anna1995',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/emily_anna1995',
    userimagename: 'annaimage',
  ),
  Flutterdevelopers(
    name: 'Peter',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/',
    userimagename: 'peterimage',
  ),
  Flutterdevelopers(
    name: 'Terry',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/',
    userimagename: 'terryimage',
  ),
  Flutterdevelopers(
    name: 'Shweta Vishwakarma',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/ShwetaVish31',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/shwetavish',
    userimagename: 'svimage',
  ),
  Flutterdevelopers(
    name: 'Abhay Patgar',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/united_emotion',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/darkbits018',
    userimagename: 'apimage',
  ),
  Flutterdevelopers(
    name: 'Jay Nirmal',
    title: 'Flutter Dev',
    twitterlink: 'https://twitter.com/Jaynirmal5',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/Jaynirmal31109',
    userimagename: 'jnimage',
  ),
  Flutterdevelopers(
    name: 'Mbah Anya',
    title: 'Flutter',
    twitterlink: 'https://twitter.com/EyesNna',
    instalink: 'www.instagram.com',
    githublink: 'https://github.com/nnaeyes6',
    userimagename: 'anyaMbah',
  ),
  Flutterdevelopers(
    name: 'Parth Panchal',
    title: 'Flutter & Python Dev',
    twitterlink: 'https://twitter.com/hitchhickerrr',
    instalink: 'https://www.instagram.com/hitchhicker.tech/',
    githublink: 'https://github.com/hitchhicker007',
    userimagename: 'hhimage',
  ),
];
